spring:
  cloud:
    stream:
      function:
        definition: processEvents;consumeEvents
      bindings:
        event-out-0:
          destination: events
        consumeEvents-in-0:
          destination: events
        processEvents-in-0:
          destination: events
        processEvents-out-0:
          destination: processed-events
      kafka:
        bindings:
          event-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
                #value:
                #  serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"